Create News API.py
Punit-Choudhary/Python-beginner-scripts pull request #123
Opened 2022-10-08 09:30 UTC by SachinDabhade

# Pull Request Template

**News API in python**

**Changes made:**<br>
mention your changes here

### Issue num (must) - #119 

### Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [x] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I am using external libraries and I have created requirements.txt in my project folder
- [x] Script is tested and running perfectly fine on my system

- [ ] PR is regarding the documentation

> If the issue was not assigned to you Please don't make a PR, It will be marked as invalid.

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## acknowledgment
- [x] I have tested my code and distributing it under GPL-3.0 License

2022-10-08 14:29 UTC, Punit-Choudhary requested changes
The file is not in the proper folder, please go through [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE)!

2022-10-09 03:02 UTC, SachinDabhade commented
I have deleted the previous file and inserted a new file, please give me a review on it if anything is wrong

2022-10-09 07:46 UTC, Punit-Choudhary requested changes
Please create `requirements.txt` for third-party libraries

2022-10-09 15:51 UTC, SachinDabhade commented
There is no requirements.txt is needed

2022-10-12 10:48 UTC, Punit-Choudhary commented
> please review this pull request...

You are using two third-party libraries:
- `wincom32` which is inside `Pywin32`
- 'requests`

Please make a folder for your project and add these requirements in `requirements.txt`

2022-10-13 08:05 UTC, SachinDabhade commented
Added Requirements.txt in appropriate directory with program

2022-10-13 12:41 UTC, Punit-Choudhary requested changes

2022-10-13 12:41 UTC, Punit-Choudhary commented on Projects/NEWS API/NEWS API.py
> +            f'https://newsapi.org/v2/top-headlines?country={country1.lower()}&category={category.lower()}&apiKey=2114b271bda54165b23a311b1d1e3c49')
API key exposed, please use `.env` to store credentials.
Refer to this blog to learn more about the environment variables 😇 
https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1

2022-10-13 16:02 UTC, SachinDabhade commented
Whta if I didn't add API key

2022-10-14 13:18 UTC, merged