snake_game
Punit-Choudhary/Python-beginner-scripts pull request #275
Opened 2024-03-29 13:02 UTC by Anmol-Sharma21

# Pull Request Template

**Feature Name:**

**Changes made:**<br>
mention your changes here

### Issue num (must) - #

### Self Check(Tick After Making pull Request)

- [ ] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [ ] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I am using external libraries and I have created requirements.txt in my project folder
- [ ] Script is tested and running perfectly fine on my system

- [ ] PR is regarding the documentation

> If the issue was not assigned to you Please don't make a PR, It will be marked as invalid.

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## acknowledgment
- [x] I have tested my code and distributing it under GPL-3.0 License

2024-03-29 14:33 UTC, Punit-Choudhary requested changes
Please remove these redundant files/folders:
- .idea/
- __pycache__/

2024-03-29 14:33 UTC, Punit-Choudhary commented on Projects/snake_game/README.md
> +This is a classic Snake game implemented in Python using the Tkinter library for GUI. The game allows the player to control a snake which moves around the screen, eating food pellets and growing long
You mentioned Tkinter, while project seems to be using turtle. If this is a typo, please fix.

2024-03-29 14:43 UTC, Anmol-Sharma21 commented
made the needful changes in the file

2024-03-29 14:48 UTC, Punit-Choudhary requested changes
Remove these unnecessary files:
- .DS_Store
- Project/.DS_Store

Please also lint your code using flake8 or any online code beautifier.

2024-03-29 15:37 UTC, Anmol-Sharma21 commented
removed the DS_store files

2024-03-30 10:44 UTC, Punit-Choudhary requested changes
Please lint your code using flake8 or any online code beutifier.

2024-03-30 10:44 UTC, Punit-Choudhary commented on Projects/snake_game/data.txt
> +15
Reset high score to 0

2024-03-30 10:44 UTC, Punit-Choudhary commented on Projects/snake_game/scoreboard.py
> +    # def game_over(self):
Remove unused code

2024-03-30 10:46 UTC, Punit-Choudhary commented
Please resolve these linting issues:

./Projects/snake_game/food.py:19:38: W292 no newline at end of file
./Projects/snake_game/main.py:35:80: E501 line too long (114 > 79 characters)
./Projects/snake_game/main.py:47:1: E303 too many blank lines (4)
./Projects/snake_game/scoreboard.py:16:80: E501 line too long (102 > 79 characters)
./Projects/snake_game/scoreboard.py:21:80: E501 line too long (102 > 79 characters)
./Projects/snake_game/snake.py:1:1: F403 'from turtle import *' used; unable to detect undefined names
./Projects/snake_game/snake.py:23:5: E303 too many blank lines (2)
./Projects/snake_game/snake.py:24:19: F405 'Turtle' may be undefined, or defined from star imports: turtle
./Projects/snake_game/snake.py:31:5: E303 too many blank lines (2)
./Projects/snake_game/snake.py:[43](https://github.com/Punit-Choudhary/Python-beginner-scripts/actions/runs/8482667203/job/23261066916?pr=275#step:4:44):5: E303 too many blank lines (3)

2024-04-02 06:38 UTC, Punit-Choudhary commented
./Projects/snake_game/main.py:35:80: E501 line too long (114 > 79 characters)
./Projects/snake_game/snake.py:1:1: F403 'from turtle import *' used; unable to detect undefined names
./Projects/snake_game/snake.py:10:1: E302 expected 2 blank lines, found 1
./Projects/snake_game/snake.py:22:19: F405 'Turtle' may be undefined, or defined from star imports: turtle

Please lint your code and resolve these.
Let me know if you want any help resolving these.

2024-04-02 09:01 UTC, Punit-Choudhary approved these changes

2024-04-02 09:02 UTC, merged

2024-04-02 09:02 UTC, Punit-Choudhary commented
Thank you for the contribution 💜 🤝